### ISSUE TITLE
JSON Redirect Question

### ISSUE THREAD

**Issue by ManFromNapa** [code4recovery/sheets#13]
I have a question about refreshing using the redirectTo parameter.  I formatted my Google Sheets and used the Google Sheets Importer to create my JSON file.  On that page it states:

> You can be redirected after refreshing by passing a redirectTo parameter to this URL.

I'm not a developer.  I tried to search for how to leverage this.  Can someone help me with some sample code?

Also, the page says: 

> Feeds that are not refreshed within 30 days are removed automatically.

Does using the "redirectTo" parameter keep my feed refreshing every time it's used?

Thanks in advance.

**Comment by ManFromNapa** [comment]
Thanks!  I've already made a copy of the Google Sheet for my group.  I can see where the redirectTo is in the LINK.  Currently it has AA San Jose's URL in there.  It looks like I need to update the script with my URL, which I just did.  Is there a way to automatically update all of the "LINKS" with the correct URL?

**Comment by ManFromNapa** [comment]
Looks like I need to update the slug which will trigger the LINK to update

**Comment by joshreisner** [comment]
That's right. The base URL is set in Extensions > App Script - right at the top

**Comment by ManFromNapa** [comment]
Thanks again Josh.

**Comment by ManFromNapa** [comment]
Josh, I would love to help with documentation for TSML.  I'm sure you get hit with a lot of questions.  I'd love to help document things to make it easier for others to implement TSML.  I also have a couple more questions.  If I'm going to ask them, why not document it for others?

**Comment by joshreisner** [comment]
Thanks! If you would like to recommend edits to make things clearer to users of the Sheets project and TSML UI, we have four "surfaces" where it would probably go.

https://tsml-ui.code4recovery.org is where we have information about how to get started with TSML UI. This is linked from a few places and is the "front door" for most users. This applies to people with all sorts of platforms, WordPress and otherwise. If they are interested in using a Google Sheet, they will see the link to:

https://sheets.code4recovery.org is where we have info to help people get started with Sheets. This probably is where we should document the baseUrl question in this thread.

https://github.com/code4recovery/tsml-ui is advanced config information for TSML UI, probably not relevant

Then we have the confirmation page, which is where you saw the original `redirectTo` mentioned. 

Feel free to submit a new ticket with suggestions on how to clarify things, or submit a PR if you're comfortable doing that.

This stuff tends to get out of date rather quickly, so I don't want to have more sites than the above floating around. TSML, the WordPress plugin, has a bunch of them and it is not the ideal situation.
